### ISSUE TITLE
'num_operands' referred before assignment

### ISSUE THREAD

**Issue by dstoutamire** [qnzhou/PyMesh#106]
A simple typo.  In CSGTree.py, variable names num_operand and num_operands are used inconsistently, leading to errors such as:

  File "/usr/local/lib/python3.6/dist-packages/pymesh/CSGTree.py", line 100, in __init__
    mid = num_operands // 2;
UnboundLocalError: local variable 'num_operands' referenced before assignment

**Comment by qnzhou** [comment]
Thanks @dstoutamire , I will fix it.
