### ISSUE TITLE
ImportError when running pymesh in docker

### ISSUE THREAD

**Issue by dlshu** [qnzhou/PyMesh#107]
Hello Mr. Zhou,

I'm a new user to pymesh. I encountered an import error when I tried to use pymesh under docker container. The error message shown in the terminal window is as follows.

> shdl@shdl-VirtualBox:~$ docker run -it qnzhou/pymesh
Python 3.6.6 (default, Jul 17 2018, 11:12:33) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/local/lib/python3.6/site-packages/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: libtbb.so.2: cannot open shared object file: No such file or directory
>>> 

Could you possibly help me figure out why the error occurred and how to fix it? My operating system is Ubuntu 16.04

Thanks a lot,
Dule

**Comment by Casyfill** [comment]
same thing here

**Comment by qnzhou** [comment]
Sorry about the glitch.  Please run `apt-get update; apt-get install -y libtbb-dev` to fix the problem temporarily.

**Comment by qnzhou** [comment]
Another option is to use the non-slim versions.  E.g.

`docker run -it --rm qnzhou/pymesh:py3.6`

**Comment by dlshu** [comment]
> Another option is to use the non-slim versions. E.g.

> `docker run -it --rm qnzhou/pymesh:py3.6`

Thanks a lot for the help. I tried both options you provided. The first option didn't fix the error, but the second option did!

![screenshot from 2018-07-24 17-17-33](https://user-images.githubusercontent.com/41606114/43166851-c25cb060-8f65-11e8-8f01-f59355de4117.png)

**Comment by qnzhou** [comment]
OK, the import error for the slim images are also fixed.  Please `docker pull qnzhou/pymesh` to update your image.
