### ISSUE TITLE
Depth map

### ISSUE THREAD

**Issue by Casyfill** [qnzhou/PyMesh#109]
Sorry guys I know it's not exactly related to PyMesh, but I feel  it is somewhat adjacent: I have a complex mesh (low-poly city 3d) and I need to generate a 2d depth map; Can I somehow compute intersection of a ray and the mesh using PyMesh?

**Comment by Casyfill** [comment]
actually sorry, it seems `pymesh.distance_to_mesh` is right what I need! 
and thanks for this awesome library!

**Comment by Casyfill** [comment]
actually, it

**Comment by qnzhou** [comment]
It seems you want to perform ray mesh intersection computation.  Have you looked into [Embree](https://embree.github.io/)?  PyMesh currently does not have interface for this, but it could become part of pymesh in the future if need.

**Comment by Casyfill** [comment]
thanks! In fact, I realized that in my case one way would be to generate voxels, and then get centroids for all the tip ones, but will check Embree as well
