### ISSUE TITLE
import pymesh failed after using docker installation

### ISSUE THREAD

**Issue by BoyuanChen** [qnzhou/PyMesh#111]
Hi,

I download the docker of pymesh directly by running: 
```
docker run -it qnzhou/pymesh
```
After this, I got the following error by running: import pymesh

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/local/lib/python3.6/site-packages/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: libtbb.so.2: cannot open shared object file: No such file or directory.

I am using Ubuntu 16.04 and the docker version is: 18.06.0-ce.

Could you please help with that?

Thank you!

**Comment by qnzhou** [comment]
This problem should have been fixed.  You just need to `docker pull qnzhou/pymesh` to get the newest image.

**Comment by BoyuanChen** [comment]
Yes, it is working now! Thanks for fixing that!

I am going to close this issue since it has been fixed.
