### ISSUE TITLE
error while loading ply file

### ISSUE THREAD

**Issue by autosquid** [qnzhou/PyMesh#13]
hi, I came across two issues while loading a mesh in ply format.

1. pymesh seems not support ply in ascii format
2. wrong reporting of duplicated property for a file with the following header:

```
element vertex 2503
property float32 x
property float32 y
property float32 z
property uint8 red
property uint8 green
property uint8 blue
property uint8 alpha
element face 4968
property list uint8 int32 vertex_indices
property list uint8 float32 texcoord
property uint8 red
property uint8 green
property uint8 blue
property uint8 alpha
end_header
```

The error message is:

```
OSError: Duplicated property name: red
PyMesh requires unique custom property names
```

However, as we can see, `red` properties belong to different elements.

**Comment by qnzhou** [comment]
ASCII ply is supported in both reading and writing.  Can you provide an example where it is not working?  

For reading and writing, I have tested loading [this file](https://www.dropbox.com/s/x40porzdqogtg3j/bun_zipper.ply?dl=0). 

    >>> import pymesh
    >>> mesh = pymesh.load_mesh("bun_zipper.ply");
    >>> pymesh.save_mesh("tmp.ply", mesh, ascii=True);                                                                                                                                

The second problem you pointed out is a limitation of PyMesh for now.  I will look into it.

**Comment by qnzhou** [comment]
The second issue is now fixed.  Please ```git pull``` to check out the latest commit (https://github.com/qnzhou/PyMesh/commit/30d772c052d1c0ec063c315e1a2af7da389a46a5).

**Comment by autosquid** [comment]
@qnzhou  Sorry, I double-checked issue 1, and it should not exist -- I missed used the mesh file. Sorry for the trouble.

The 2nd issue is perfectly solved now. (though prefix of 'vertex' or 'face' are added to property name, which I think is all right).

I am closing the issue now.

**Comment by petern3** [comment]
I apologize to bring this issue up again, but I'm having other problems with a PLY. The relevant part of the traceback is:
```
  File "/usr/local/lib/python2.7/dist-packages/pymesh-0.1-py2.7.egg/pymesh/meshio.py", line 21, in load_mesh
    factory.load_file(filename);
  File "/usr/local/lib/python2.7/dist-packages/pymesh-0.1-py2.7.egg/pymesh/swig/PyMesh.py", line 621, in load_file
    return _PyMesh.MeshFactory_load_file(self, filename)
IOError: Cannot find required property"vertex_indices" in face element section.
```
I can't find a face element either (in the first 50 lines which contains the header), and the rest of the file appears to be binary.

```
ply
format binary_little_endian 1.0
comment PCL generated
element vertex 3494419
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
Z�%@Z�>U...
```

When I open the file with CloudCompare, an error appears which says it's missing two columns, but it is still able to load the points (at the very least x,y,z and r,g,b). It opens fine in Blender.

Thanks!

**Comment by qnzhou** [comment]
It seems the .ply file represent a point cloud.  I have removed the check for "vertex_indices" field.  Could you shared the .ply file for testing purpose?

**Comment by petern3** [comment]
You're quite right, it is a point cloud. You can find the file here:
https://dl.dropboxusercontent.com/u/27722501/metallic_sphere2.ply

**Comment by qnzhou** [comment]
Should be solved now.  Please `git pull` and rebuild.

**Comment by petern3** [comment]
That was quick!  I can confirm that it works, and you've saved me some hard effort in Octave.
