### ISSUE TITLE
'igl/copyleft/cgal/delaunay_triangulation.h' file not found

### ISSUE THREAD

**Issue by grpaulfr** [qnzhou/PyMesh#14]
I followed your installation instructions in the documentation, everything goes well until `make tools` when I get the following error:

```
[ 65%] Building CXX object tools/Triangulation/CMakeFiles/lib_triangulation.dir/IGL/DelaunayTriangulation.cpp.o
/Users/grpaul/myapps/PyMesh/tools/Triangulation/IGL/DelaunayTriangulation.cpp:4:10: fatal error: 
      'igl/copyleft/cgal/delaunay_triangulation.h' file not found
#include <igl/copyleft/cgal/delaunay_triangulation.h>
```

Checking a little bit the files, it actually does not exist. It seems that it is defined in `igl/copyleft/cgal/remesh_intersections.cpp`... as a lambda? Really looking forward to try your library!

**Comment by qnzhou** [comment]
Just pushed a fix.  Could you ```git pull``` and ```git submodule update third_party/libigl```?  The error should be gone now.

I am currently working on the triangulation module, it got merged into master by accident.

**Comment by grpaulfr** [comment]
Thanks a lot for your fast response. I could now compile correctly, and all tests are passed successfully. Nonetheless, when I make the last test of importing the PyMesh module I get the following error:
```
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```
Googling a little bit, it seems to be a problem related to linking against different python version... The problem is that I don't know if it is related to the same problem. Before closing this issue it would be nice to know. I will investigate on my side, but maybe you have an idea.

Thanks again for your fast answer!

**Comment by grpaulfr** [comment]
Maybe this helps, but in the output from `./setup.py install` I get:
```
package init file 'python/pymesh/tests/__init__.py' not found (or not a regular file)
package init file 'python/pymesh/meshutils/tests/__init__.py' not found (or not a regular file)
package init file 'python/pymesh/wires/tests/__init__.py' not found (or not a regular file)
```

**Comment by qnzhou** [comment]
One way to find out for use is to look at `CMakeCache.txt` file:

```
grep PYTHON_EXECUTABLE:FILEPATH $PYMESH_PATH/build/CMakeCache.txt
grep PYTHON_LIBRARY:FILEPATH $PYMESH_PATH/build/CMakeCache.txt
```

If the interpreter and the library is of different version, it could cause the above error.

**Comment by grpaulfr** [comment]
I get the following, it seems that they match:

```
PYTHON_EXECUTABLE:FILEPATH=/Users/grpaul/anaconda/bin/python
PYTHON_LIBRARY:FILEPATH=/Users/grpaul/anaconda/lib/libpython2.7.dylib
```
and `/Users/grpaul/anaconda/bin/python --version` gives me:
```
Python 2.7.12 :: Anaconda custom (x86_64)
```

Does it help?

**Comment by qnzhou** [comment]
That is strange.  Your python library seems to match the executable.

Can you run `which python` to make sure it is `/Users/grpaul/anaconda/bin/python`?  and perhaps check `otool -L /Users/grpaul/anaconda/bin/python` to see if it depends `/Users/grpaul/anaconda/lib/libpython2.7.dylib`

**Comment by grpaulfr** [comment]
I know this is strange.

`which python` gives:
```
/Users/grpaul/anaconda/bin/python
```

and `otool -L /Users/grpaul/anaconda/bin/python`:
```
/Users/grpaul/anaconda/bin/python:
	@rpath/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 635.21.0)
```

This seems compatible. This is indeed strange. 

I successfully compiled and installed everything on a linux workstation. It is probably a problem with my laptop running OSX El Capitan. I think you should close this issue. I will open one, because the tests return an error ;)
