### ISSUE TITLE
Ubuntu 16.04 installation issue

### ISSUE THREAD

**Issue by rhs2132** [qnzhou/PyMesh#16]
When installing on Ubuntu 16.04, I am getting the following issue while running "make tools" at 75%:

/usr/bin/ld: cannot find -llib_triangle_wrapper
/usr/bin/ld: /home/rsmith/software/cork-master/lib/libcork.a(cork.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/rsmith/software/cork-master/lib/libcork.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

I had a similar error when linking to the libtriangles-dev library. I tried adding the fPIC option to cmakecache.txt but haven't been able to get it to work. What should I try next? Let me know if I can provide any helpful system information.

**Comment by qnzhou** [comment]
Have you tried building triangle, cork from the `third_party` folder?  I.e.

```
cd $PYMESH_PATH/third_party
mkdir build
cd build
cmake ..
make
make install
```

**Comment by rhs2132** [comment]
It turns out that I didn't do a recursive clone on PyMesh, so all of the third party directories were empty. I manually installed those libraries on my system, but PyMesh didn't really like that. I just did the recursive clone and everything built perfectly with all tests passing).

It is not however finding BSP libraries, cheev_, and pthread.h. Do you have a recommended installation process for those?

Thanks

**Comment by qnzhou** [comment]
BSP is a private library which I included for research purposes.  PyMesh should work fine without it.  I have never encountered missing cheev_ and pthread.h.  Do they break the compilation?  If so, how come you are able to run unit tests?
