### ISSUE TITLE
make tools_tests failed on Ubuntu

### ISSUE THREAD

**Issue by hpbui** [qnzhou/PyMesh#28]
Hello,
When I run "make tools_tests", and get these errors:

[ 58%] Linking CXX executable ../../../../bin/triangulation_tests
[==========] Running 8 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from LexicographicTriangulationTest
[ RUN      ] LexicographicTriangulationTest.simple
unknown file: Failure
C++ exception with description "Triangulation engine igl_lexicographic is not supported" thrown in the test body.
[  FAILED  ] LexicographicTriangulationTest.simple (0 ms)
[ RUN      ] LexicographicTriangulationTest.simple2
unknown file: Failure
C++ exception with description "Triangulation engine igl_lexicographic is not supported" thrown in the test body.
[  FAILED  ] LexicographicTriangulationTest.simple2 (0 ms)
[ RUN      ] LexicographicTriangulationTest.simple3
unknown file: Failure
C++ exception with description "Triangulation engine igl_lexicographic is not supported" thrown in the test body.
[  FAILED  ] LexicographicTriangulationTest.simple3 (0 ms)
[ RUN      ] LexicographicTriangulationTest.degenerate
unknown file: Failure
C++ exception with description "Triangulation engine igl_lexicographic is not supported" thrown in the test body.
[  FAILED  ] LexicographicTriangulationTest.degenerate (0 ms)
[----------] 4 tests from LexicographicTriangulationTest (0 ms total)

Do you have any idea please? Thank you!
Notice that I followed all installation steps.

**Comment by qnzhou** [comment]
Sorry for the late response, could you check to see if `libigl` is found by cmake with the following command?

```
 grep -i libigl $PYMESH_PATH/build/CMakeCache.txt
```

For example, I got the following output:

```
LIBIGL_INCLUDE_DIRS:PATH=/Users/qzhou/Research/libigl/include
//Details about finding LIBIGL
FIND_PACKAGE_MESSAGE_DETAILS_LIBIGL:INTERNAL=[/Users/qzhou/Research/libigl/include][v()]
//ADVANCED property for variable: LIBIGL_INCLUDE_DIRS
LIBIGL_INCLUDE_DIRS-ADVANCED:INTERNAL=1
```

**Comment by hpbui** [comment]
Thank you for your reply!
I got this:
LIBIGL_INCLUDE_DIRS:PATH=/home/huu/dev/PyMesh/third_party/libigl/include
//Details about finding LIBIGL
FIND_PACKAGE_MESSAGE_DETAILS_LIBIGL:INTERNAL=[/home/huu/dev/PyMesh/third_party/libigl/include][v()]
//ADVANCED property for variable: LIBIGL_INCLUDE_DIRS
LIBIGL_INCLUDE_DIRS-ADVANCED:INTERNAL=1

It's still failed when running make tools_tests

**Comment by qnzhou** [comment]
I see the problem.  Could you `git pull` and try rebuild the tests?  Thanks!

**Comment by hpbui** [comment]
Good! It's fine now. Thank you!!
