### ISSUE TITLE
Compile error on python 3 (anaconda)

### ISSUE THREAD

**Issue by MelSyAzis** [qnzhou/PyMesh#29]
cmake cannot complete the configuration with the following output:

```
Traceback (most recent call last):
  File "/home/hazmil/Software/pythonPackages/PyMesh/cmake/SetInstallRpath.py", line 23, in <module>
    site_location = [os.path.join(loc, install_path) for loc in site_location] +\
  File "/home/hazmil/Software/pythonPackages/PyMesh/cmake/SetInstallRpath.py", line 23, in <listcomp>
    site_location = [os.path.join(loc, install_path) for loc in site_location] +\
  File "/home/hazmil/Software/anaconda3/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
CMake Error at Settings.cmake:58 (INCLUDE):
  include could not find load file:

    SetInstallRpath
Call Stack (most recent call first):
CMakeLists.txt:16 (INCLUDE)
```

Using python 2.7, I can get the cmake configuration completed if I add "/" in front of defined paths in the script "SetInstallRpath.py" (due to another type of error), then can successfully complete the compilation (with a few failed test cases). However, I encountered an error when trying to import "pymesh", and I relate this to a latest requirement in the home address of Pymesh which is  

> PyMesh depends on the following tools/libraries:    Python v3.x.

Then I changed to Python 3 to work with this package, however encountered with the above error.

**Comment by qnzhou** [comment]
Thanks for the report!

For python 2.7, could you show me your
`${PYMESH_PATH}/cmake/SetInstallRpath.cmake` file?  It is strange that you
need to append `/` to get it working.

For python 3.1, could you let me know the output of the following commands?

```
python -c "import site; print(site.getsitepackages())"
```

and

```
python -c "import site; print(site.getusersitepackages())"
```

**Comment by almost** [comment]
I'm having the same issue, here are the outputs of those commands:

```
[master] build $  python -c "import site; print(site.getsitepackages())"
 python -c "import site; print(site.getsitepackages())"
['/Users/tom/anaconda/lib/python3.5/site-packages']
[master] build $ python -c "import site; print(site.getusersitepackages())"
python -c "import site; print(site.getusersitepackages())"
/Users/tom/.local/lib/python3.5/site-packages
[master] build $ python --version
python --version
Python 3.5.1 :: Anaconda custom (x86_64)
[master] build $  
```

So it looks like site.getsitepackages() is returning a list when a string was expected. Needs to be concatenated onto the list not appended.

**Comment by almost** [comment]
Oh I see you've already fixed this in development branch. I also found I could just updated that one line and that fixes it in master.

So for anyone else having this issue open `build/cmake/SetInstall.py` and change this line:

```
    site_location.append(site.getsitepackages());
```

To this:

```
    site_location += site.getsitepackages()
```

**Comment by qnzhou** [comment]
Thanks Thomas!  I thought I have pushed this change to master branch.  The master branch should now be up-to-date with development branch.
