### ISSUE TITLE
Compiling with Carve

### ISSUE THREAD

**Issue by jdumas** [qnzhou/PyMesh#3]
Hi James,

I was just trying to compile PyMesh recently with the Carve library, but I'm getting some compilation issues. It's complaining with stuff like `error: ‘meshset_t’ in ‘class carve::csg::CSG’ does not name a type`. Which version of Carve are you using? The type `meshset_t` is never defined in the archive I can download from the [Google Code archive](https://code.google.com/archive/p/carve/) (v1.4.0), but it is defined in [this fork](https://github.com/VTREEM/Carve) from Github. If you are using the latter, maybe you could update the documentation accordingly?

**Comment by qnzhou** [comment]
Hi Dumas,

I am using a modified carve repo: https://github.com/qnzhou/carve

Could you give it a try?  I will update the doc. Thanks for pointing it out.

best,
James

**Comment by jdumas** [comment]
Yep, that's it. I didn't see you had forked version. It compiles fine with it =)
