### ISSUE TITLE
Python not found within virtualenv

### ISSUE THREAD

**Issue by themmes** [qnzhou/PyMesh#31]
All dependencies are successfully installed and found, but Python itself is still missing,

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Python library is not found.  Please ensure python is installed (missing:
  PYTHON_INCLUDE_DIRS PYTHON_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPython.cmake:50 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindAllDependencies.cmake:10 (FIND_PACKAGE)
  Settings.cmake:51 (FIND_PACKAGE)
  CMakeLists.txt:16 (INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/home/tom/vision/env/PyMesh/build/CMakeFiles/CMakeOutput.log".
```

Now I tried adding explicit statements for the location of python, like @dansand suggests (here: https://github.com/qnzhou/PyMesh/issues/5):

```
cmake DPYTHON_INCLUDE_DIR=/home/tom/vision/env/include/python3.5m -DPYTHON_LIBRARY=/home/tom/vision/env/lib/python3.5 -DPYTHON_EXECUTABLE=/home/tom/vision/bin/python3.5 -DPYTHON_PACKAGES_PATH=/home/tom/vision/env/lib/python3.5/site-packages ..
```

However that does not solve it. Could you maybe point me in the right direction?

Thanks in advance!

**Comment by qnzhou** [comment]
Ah, I rewrote the `FindPython.cmake` because the original one provided by cmake does not work well with `virtualenv`.  I must have missed some cases (assuming you are using the latest code).

Could you check that `python -c "import sys; print(sys.base_prefix)"` makes sense?  I think it should output `/home/tom/vision/env/`.

**Comment by themmes** [comment]
Thats correct!

```
(env) tom@vision:~/vision/env$ python -c "import sys; print(sys.base_prefix)"
/home/tom/vision/env
```

**Comment by qnzhou** [comment]
Hmmm, can you double check the following files exists:

```
/home/tom/vision/env/include/python3.5m/Python.h
```

and 

```
/home/tom/vision/env/lib/python3.5/config-3.5m/libpython3.5.*
```

These are the files I look for in my `FindPython.cmake` script.  If they are in a different directory, please let me know so I could add them to the search path.

**Comment by themmes** [comment]
For `Python.h` it finds nothing...

For `libpython` it finds;
```
(env) tom@vision:~/vision/env$ locate libpython3.5
/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5.so
/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so
/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1
/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
... (some more doc and info files)
```

**Comment by qnzhou** [comment]
Thanks for bearing with me.  It is really strange `Python.h` is missing.  In that case, what are the files in `/home/tom/vision/env/include/python3.5m/`?  Which linux distribution you are using?  If debian/ubuntu, can you check if `python-dev` is installed.

**Comment by themmes** [comment]
Looks like this;
```
(env) tom@vision:~/vision/env/include$ ls -lh
total 0
lrwxrwxrwx 1 tom tom 23 mrt 13 21:03 python3.5m -> /usr/include/python3.5m
(env) tom@vision:~/vision/env/include$ cd python3.5m
(env) tom@vision:~/vision/env/include/python3.5m$ ls
Imaging.h  ImDib.h  ImPlatform.h
```

`python-dev` is installed

I'm running;
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by qnzhou** [comment]
It is pretty strange.  I just tested your setup on a clean slake of ubuntu.  Here is my system info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

Here is what I did:

```
apt-get update
apt-get install python3 libpython3-dev virtualenv git cmake swig gcc g++ libeigen3-dev
mkdir ~/tmp
virtualenv --python=python3 ~/tmp
source ~/tmp/bin/activate
pip install numpy scipy nose
git clone https://github.com/qnzhou/PyMesh.git
cd PyMesh
mkdir build
cd build
cmake ..
```

and `cmake` find python just fine.  Did you see anything different in your setup?

**Comment by themmes** [comment]
Well that's just really weird, I just removed my `env` and redid the process following your commands. Now it works brilliantly. Sorry for taking your time, hopefully I can contribute something during the coming months (graduation).
