### ISSUE TITLE
Orientation in Convex Hull

### ISSUE THREAD

**Issue by jdumas** [qnzhou/PyMesh#52]
Hi James,

The your convex hull wrapper, you are reorienting the facets of the convex hull based on the center of the bouding box of the hull. However, this center is not always inside the convex hull. You can take instead the barycenter of the points on the convex hull, which is guaranteed to be inside the hull, as a reference point instead.

**Comment by qnzhou** [comment]
Good catch!  Is it true to claim the bbox center is either inside or on the boundary of the convex hull?  I.e. the bbox center cannot be outside, right?

**Comment by jdumas** [comment]
I'm not so sure about that either. It seems to be the case in 2D, but not is 3D. Look at [this decomposition of the cube](https://www.ics.uci.edu/~eppstein/projects/tetra/) into 5 tetrahedra for example.

**Comment by qnzhou** [comment]
I see.  Thanks Jérémie!
