### ISSUE TITLE
make src_tests : Undefined reference to process(std::__cxx11::basic_string ... ) 

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [qnzhou/PyMesh#55]
I ran into this issue on Ubuntu 16.04 after the third party libs were installed smoothly and make completed.
[This thread](https://stackoverflow.com/questions/37004976/undefined-reference-to-processstd-cxx11basic-string-when-compiling-a) helped me solve it (thanks a lot for your help in finding this link @qnzhou ).

I just had to rebuild with gcc < 5 and the tests were successful.

**Comment by qnzhou** [comment]
Thanks Thibault!
