### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by hpbader42** [qnzhou/PyMesh#63]
Hi, I'm trying and failing to compile PyMesh. I don't know exactly what is going wrong, but I'm trying to use make with gcc4.9 to compile everything. My output files state something about C++14 needing to be enabled, though I have made sure that the compiler flags include -std=c++14. It looks like it may be an issue getting pybind11 to play nicely with Eigen 3.3, but I'm currently just trying to install this and am having trouble finding what I need to change. Any ideas?

/home/motion/PyMesh/python/PyFEM.cpp: In function ‘void init_FEM(pybind11::module&)’:
/home/motion/PyMesh/python/PyFEM.cpp:24:73: error: ‘const_’ is not a member of ‘py’
         .def("get_density", py::overload_cast<>(&Material::get_density, py::const_), "Get denisity (uniform material only).")
                                                                         ^
In file included from /home/motion/PyMesh/third_party/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/motion/PyMesh/third_party/pybind11/include/pybind11/cast.h:13,
                 from /home/motion/PyMesh/third_party/pybind11/include/pybind11/attr.h:13,
                 from /home/motion/PyMesh/third_party/pybind11/include/pybind11/pybind11.h:43,
                 from /home/motion/PyMesh/python/PyFEM.cpp:3:
/home/motion/PyMesh/third_party/pybind11/include/pybind11/detail/common.h: In instantiation of ‘struct pybind11::overload_cast<>’:
/home/motion/PyMesh/python/PyFEM.cpp:24:83:   required from here
/home/motion/PyMesh/third_party/pybind11/include/pybind11/detail/common.h:752:5: error: static assertion failed: pybind11::overload_cast<...> requires compiling in C++14 mode
     static_assert(detail::deferred_t<std::false_type, Args...>::value,
     ^
/home/motion/PyMesh/python/PyFEM.cpp:25:80: error: ‘const_’ is not a member of ‘py’
         .def("get_density", py::overload_cast<VectorF>(&Material::get_density, py::const_), "Get density at specific point.")
                                                                                ^
In file included from /home/motion/PyMesh/third_party/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/motion/PyMesh/third_party/pybind11/include/pybind11/cast.h:13,
                 from /home/motion/PyMesh/third_party/pybind11/include/pybind11/attr.h:13,
                 from /home/motion/PyMesh/third_party/pybind11/include/pybind11/pybind11.h:43,
                 from /home/motion/PyMesh/python/PyFEM.cpp:3:
/home/motion/PyMesh/third_party/pybind11/include/pybind11/detail/common.h: In instantiation of ‘struct pybind11::overload_cast<Eigen::Matrix<double, -1, 1, 0, -1, 1> >’:
/home/motion/PyMesh/python/PyFEM.cpp:25:90:   required from here
/home/motion/PyMesh/third_party/pybind11/include/pybind11/detail/common.h:752:5: error: static assertion failed: pybind11::overload_cast<...> requires compiling in C++14 mode
     static_assert(detail::deferred_t<std::false_type, Args...>::value,

**Comment by qnzhou** [comment]
I suspect it is caused by gcc4.9 does not fully support some of the c++14 features that pybind11 uses.  However, just to be sure, can you `git pull` and try compile again?

**Comment by hpbader42** [comment]
It didn't work after the update, so I tried upgrading my gcc to version 5. After that, I got this error:

/usr/bin/ld: _ZGVZN4CGAL18get_default_randomEvE14default_random: TLS definition in ../../python/pymesh/lib/libself_intersection.a(IGLSelfIntersectionResolver.cpp.o) section .tbss._ZGVZN4CGAL18get_default_randomEvE14default_random[_ZGVZN4CGAL18get_default_randomEvE14default_random] mismatches non-TLS reference in ../../python/pymesh/lib/libtetrahedronization.a(CGALMeshGen.cpp.o)

I was able to get it to compile by telling selfIntersection and tetrahedralization to be added as static libraries instead of shared libraries, and I also had to go into the IGL folder and change its options so that it would compile statically.

**Comment by buaaswf** [comment]
I also meet this problem, error: static assertion failed: pybind11::overload_cast<...> requires compiling in C++14 mode
did you solve this well ?

**Comment by dangom** [comment]
@buaaswf See pybind11 docs [here](https://pybind11.readthedocs.io/en/stable/classes.html#overloaded-methods).
You can change overload_cast for a "shim" overload_cast_ that works with older compilers as shown below:

instead of:

```
py::class_<Pet>(m, "Pet")
    .def("set", py::overload_cast<int>(&Pet::set), "Set the pet's age")
    .def("set", py::overload_cast<const std::string &>(&Pet::set), "Set the pet's name");

```
do

```
template <typename... Args>
using overload_cast_ = pybind11::detail::overload_cast_impl<Args...>;

py::class_<Pet>(m, "Pet")
    .def("set", overload_cast_<int>()(&Pet::set), "Set the pet's age")
    .def("set", overload_cast_<const std::string &>()(&Pet::set), "Set the pet's name");

```
