### ISSUE TITLE
Gmsh Connectivity Problem

### ISSUE THREAD

**Issue by Meiyim** [qnzhou/PyMesh#69]
Hi, @qnzhou .

I load a simple gmsh file with 
`mesh = pymesh.load_mesh('cavity.msh')`
and enable connectivity function with
`mesh.enable_connectivity()`

the number of faces, vertices and elements are good, but when i check the connectivity of face-voxel, it seems no connections has been found.
`for i in xrange(mesh.num_elements):
    print mesh.get_voxel_adjacent_faces(i)`

after checking the gmsh file, i'm sure there are face and voxelssharing more than 2 vertices.
[cavity.msh.tar.gz](https://github.com/qnzhou/PyMesh/files/1583941/cavity.msh.tar.gz)

**Comment by qnzhou** [comment]
Should be fixed now.  Thanks for reporting.
