### ISSUE TITLE
Third_party installation issue: ‘nullptr’ was not declared

### ISSUE THREAD

**Issue by ademsaglam** [qnzhou/PyMesh#73]
Hello,

I have an issue in installing the third_party files. I use:
- Ubuntu 16.04
- g++ version 5.4.0

After 5% of installation progress, I get the followin gerror message:

[  5%] Built target carve
Scanning dependencies of target carve_fileformats
[  5%] Building CXX object carve/common/CMakeFiles/carve_fileformats.dir/read_ply.cpp.o
/home/adem/bin/PyMesh/third_party/carve/common/read_ply.cpp: In member function ‘virtual void {anonymous}::line_idx::length(size_t)’:
/home/adem/bin/PyMesh/third_party/carve/common/read_ply.cpp:64:48: error: ‘nullptr’ was not declared in this scope

I checked on the internet, some people say that this is an issue when one used an older version of g++ (older than 4.6), but in my case it should be fine.
Anyone knows the origin of the problem?

Kind regards.

**Comment by qnzhou** [comment]
This does look like a compiler's c++11 support issue.  Does the following code compile?

```
int main(int argc, char** argv) {
    char *a = nullptr;
    return 0;
}
```

Compile with `g++ -std=c++11 -o a test.cpp`

**Comment by ademsaglam** [comment]
Thank you for the suggestion. I tried it and it worked properly.

When I do "cmake .." in the third_party folder, I get this output (I just copied part of it):

-- ************************************************************
-- ***    Eigen's unit tests configuration summary          ***
-- ************************************************************
-- 
-- Build type:        Release
-- Build site:        server
-- Build string:      linux-4.13.0-32-generic-_-5.4.0-sse2-64bit
-- Enabled backends:  MPFR C++, 
-- Disabled backends: GoogleHash,  Adolc,  fftw,  OpenGL, 
-- Default order:     Column-major
-- Maximal matrix/vector size: 320
-- SSE2:              Using architecture defaults
-- SSE3:              Using architecture defaults
-- SSSE3:             Using architecture defaults
-- SSE4.1:            Using architecture defaults
-- SSE4.2:            Using architecture defaults
-- AVX:               Using architecture defaults
-- FMA:               Using architecture defaults
-- AVX512:            Using architecture defaults
-- Altivec:           Using architecture defaults
-- VSX:               Using architecture defaults
-- ARM NEON:          Using architecture defaults
-- ARMv8 NEON:        Using architecture defaults
-- S390X ZVECTOR:     Using architecture defaults
-- C++11:             OFF
-- SYCL:              OFF
-- CUDA:              OFF
-- 


There, it shows that C++11 is OFF. Might this be the problem? I have to reinstall Eigen then?

**Comment by ademsaglam** [comment]
I solved the problem by executing cmake with the following flag:

cmake .. -DCMAKE_CXX_FLAGS="-std=c++11"

Thank you very much for your guidance.

**Comment by qnzhou** [comment]
I have updated the cmake build system.  Hopefully, it is no longer necessary to use your walk around.
