### ISSUE TITLE
boundary_loops method for meshes returns Swig error message

### ISSUE THREAD

**Issue by toddesparks** [qnzhou/PyMesh#76]
Using the boundary_loops method on a slice from a pymesh.slice_mesh result returns:

<Swig Object of type 'std::vector< Eigen::VectorXi,std::allocator< Eigen::VectorXi > > *' at 0x7fdba93c51e0>swig/python detected a memory leak of type 'std::vector< Eigen::VectorXi,std::allocator< Eigen::VectorXi > > *', no destructor found.

**Comment by qnzhou** [comment]
You are probably using an older version of pymesh.  I have switched from SWIG to PyBind11 a while back.  Here is my attempt of reproducing the problem:

```python
>>> import pymesh
>>> import numpy as np
>>> ball = pymesh.generate_icosphere(1.0, np.zeros(3))
>>> slices = pymesh.slice_mesh(ball, [0, 0, 1], 2)
>>> slices
[<pymesh.Mesh.Mesh object at 0x109b82d10>, <pymesh.Mesh.Mesh object at 0x109b82d90>]
>>> slices[0].boundary_loops
[array([ 8,  7,  5,  2,  0,  1,  3,  4,  6,  9, 11, 10], dtype=int32)]
>>> slices[1].boundary_loops
[array([ 8,  7,  5,  2,  0,  1,  3,  4,  6,  9, 11, 10], dtype=int32)]
```

**Comment by toddesparks** [comment]
I installed via pip, so that is very likely the case.
