### ISSUE TITLE
HashMapTrait and sparsehash

### ISSUE THREAD

**Issue by jdumas** [qnzhou/PyMesh#8]
Hi James,

This is a small issue, but currently preventing me from compiling PyMesh. In `Misc/HashMapTrait.h`, you should not include the sparsehash headers under the `PyMesh` namespace, as it is done currently (it leads to a compilation error on my machine with sparsehash 2.0.3 and gcc 6.1.1).

**Comment by qnzhou** [comment]
Thanks Jérémie!  It should be fixed now.

**Comment by jdumas** [comment]
Yep, looks good now =)
