### ISSUE TITLE
AttributeError: module 'PyMesh' has no attribute 'triangle

### ISSUE THREAD

**Issue by riaqn** [qnzhou/PyMesh#80]
```
Traceback (most recent call last):
  File "split.py", line 2, in <module>
    import pymesh
  File "/home/riaqn/doll/codes/ENV/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/__init__.py", line 22, in <module>
    from .convex_hull import convex_hull
  File "/home/riaqn/doll/codes/ENV/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/convex_hull.py", line 5, in <module>
    from .triangle import triangle
  File "/home/riaqn/doll/codes/ENV/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/triangle.py", line 4, in <module>
    class triangle(PyMesh.triangle):
AttributeError: module 'PyMesh' has no attribute 'triangle
```

**Comment by qnzhou** [comment]
It seems the triangle module is not compiled.  Did all unit tests pass?

```
cd $PYMESH_PATH/build
make all_tests
```

**Comment by riaqn** [comment]
Hi @qnzhou thanks for the reply.
```
[----------] 12 tests from TriangleWrapperTest
[ RUN      ] TriangleWrapperTest.Creation
[       OK ] TriangleWrapperTest.Creation (1 ms)
[ RUN      ] TriangleWrapperTest.Holes
[       OK ] TriangleWrapperTest.Holes (0 ms)
[ RUN      ] TriangleWrapperTest.AutoHoleDetection
[       OK ] TriangleWrapperTest.AutoHoleDetection (0 ms)
[ RUN      ] TriangleWrapperTest.3D
[       OK ] TriangleWrapperTest.3D (0 ms)
[ RUN      ] TriangleWrapperTest.Refine
[       OK ] TriangleWrapperTest.Refine (1 ms)
[ RUN      ] TriangleWrapperTest.3DWithHoles
[       OK ] TriangleWrapperTest.3DWithHoles (2 ms)
[ RUN      ] TriangleWrapperTest.debug2
[       OK ] TriangleWrapperTest.debug2 (1 ms)
[ RUN      ] TriangleWrapperTest.refinement
[       OK ] TriangleWrapperTest.refinement (1 ms)
[ RUN      ] TriangleWrapperTest.point_cloud
[       OK ] TriangleWrapperTest.point_cloud (0 ms)
[ RUN      ] TriangleWrapperTest.convex_hull
[       OK ] TriangleWrapperTest.convex_hull (0 ms)
[ RUN      ] TriangleWrapperTest.conforming
[       OK ] TriangleWrapperTest.conforming (6 ms)
[ RUN      ] TriangleWrapperTest.self_intersecting_segments
[       OK ] TriangleWrapperTest.self_intersecting_segments (0 ms)
[----------] 12 tests from TriangleWrapperTest (13 ms total)

[----------] Global test environment tear-down
[==========] 14 tests from 2 test cases ran. (13 ms total)
[  PASSED  ] 14 tests.

  YOU HAVE 1 DISABLED TEST
```

**Comment by qnzhou** [comment]
Hmmm.  What about `python -c "import pymesh; pymesh.test()"`?  Does it give any errors?

**Comment by riaqn** [comment]
The program will fail on `import` immediately, and same error. 

Question: besides the `.py` files, do I also have to install the C++ library(`.so`) too? I remember the `setup.py` script didn't do that.

Also, I'm using a `virtualenv` environment, not sure if that can be a problem, tho.

**Comment by qnzhou** [comment]
Yes, you do need to install the `.so` libraries, too.  Did you build and `setup.py install` inside of the `virtualenv`?  Can you check if the following directory exists and is not empty?

```
/home/riaqn/doll/codes/ENV/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/lib
```

and

```
/home/riaqn/doll/codes/ENV/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/third_party/lib
```

**Comment by riaqn** [comment]
Hi, the first one exists and is not empty.
```
total 16M
-rwxr-xr-x 1 riaqn riaqn  453K Mar 19 13:44 libassembler.so*
-rwxr-xr-x 1 riaqn riaqn  5.0M Mar 19 13:44 libboolean.so*
-rwxr-xr-x 1 riaqn riaqn  138K Mar 19 13:44 libcgal_wrapper.so*
-rwxr-xr-x 1 riaqn riaqn  330K Mar 19 13:44 libconvex_hull.so*
-rw-r--r-- 1 riaqn riaqn  676K Mar 19 13:44 libgmock.a
-rw-r--r-- 1 riaqn riaqn  511K Mar 19 13:44 libgtest.a
-rwxr-xr-x 1 riaqn riaqn 1003K Mar 19 13:44 libMesh.so*
-rwxr-xr-x 1 riaqn riaqn  644K Mar 19 13:44 libMeshUtils.so*
-rw-r--r-- 1 riaqn riaqn  142K Mar 19 13:44 libpredicates.a
-rwxr-xr-x 1 riaqn riaqn  963K Mar 19 13:44 libtetgen_wrapper.so*
-rwxr-xr-x 1 riaqn riaqn  5.1M Mar 19 13:44 libtetrahedronization.so*
-rwxr-xr-x 1 riaqn riaqn  468K Mar 19 13:44 libtriangle_wrapper.so*
```

The second on doesn't exist - I didn't build third party libraries because I built them myself. They are located under `/usr/lib` and `/usr/local/lib`. I hope that's OK?

Also, in which working directory should I run `setup.py install`? Should it be the `PyMesh` source dir, or the building directory?

**Comment by qnzhou** [comment]
Ah, no, third party libraries are not statically linked.  I think if you `ldd libtriangle_wrapper.so`, you will see a few dependencies not found.

On the other hand, libraries from third-party won't pollute your file system since they won't be installed in `/usr/lib` or `/opt/local/lib`.  Instead, they will be kept under the `pymesh` directory in python's `site-package` directory.

**Comment by riaqn** [comment]
Hi, interestingly `libtriangle_wrapper.so` is well-linked:
```
	linux-vdso.so.1 (0x00007ffe4fded000)
	libMeshUtils.so => /home/riaqn/doll/codes/PyMesh/python/pymesh/lib/libMeshUtils.so (0x00007fb87edd5000)
	libMesh.so => /home/riaqn/doll/codes/PyMesh/python/pymesh/lib/libMesh.so (0x00007fb87eb1f000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb87e798000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb87e44c000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fb87e21e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb87e007000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb87dde9000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb87da32000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007fb87f2ba000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb87d82e000)
```
what concerns me, however, is that things like `libMeshUtils.so` is not linked to the one under `site-packages`, but in the source directory. Do you think this could be the problem?

**Comment by riaqn** [comment]
OK I now follow the instruction strictly, and it's some new error:
```
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/lib/python3.6/site-packages/pymesh2-0.1.14-py3.6-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: /home/riaqn/doll/codes/PyMesh/python/pymesh/lib/libboolean.so: undefined symbol: _Z26computeSymmetricDifference11CorkTriMeshS_PS_
```

**Comment by riaqn** [comment]
So this function seems to be from cork, and I notice that cork is statically linked.. can that be a problem?

I changed cork to shared library and let's see how that will go..

**Comment by qnzhou** [comment]
That is really strange.  Maybe cmake is not using the right cork library?
```
grep CORK_LIBRARIES $PYMESH_PATH/build/CMakeCache.txt 
```
This command should point to something like `$PYMESH_PATH/python/pymesh/third_party/lib/libcork.a`

**Comment by riaqn** [comment]
Ahh it seems that I installed libcork system-wide before, so cmake uses the `libcork.so` instead of `libcork.a`, so cork is not statically linked to pymesh, and python can't load system wide shared libraries, I guess. Therefore the linking error.

**Comment by riaqn** [comment]
BTW, can you tell me where the gaussian curvature estimation is implemented? I'm looking at CGAL[1] now and wondering which one should I choose.

https://doc.cgal.org/latest/Jet_fitting_3/index.html

**Comment by qnzhou** [comment]
For Gaussian curvature computation, see 
https://github.com/qnzhou/PyMesh/blob/master/src/Attributes/VertexGaussianCurvatureAttribute.h
and
https://github.com/qnzhou/PyMesh/blob/master/src/Attributes/VertexGaussianCurvatureAttribute.cpp

**Comment by riaqn** [comment]
I get it wroking now. Thank you for walking me through. I do feel there is room for improvement in the building process.

**Comment by jared-slone** [comment]
Any chance you could be more specific about how you resolved the error. I am having the same problem on my machine, Windows 10
