### ISSUE TITLE
Distance to mesh complexity

### ISSUE THREAD

**Issue by dragostis** [qnzhou/PyMesh#87]
What's the complexity of `distance_to_mesh`? I would require a very similar functionality, but one that returns back faces instead of points on the mesh. In order to recover the faces, I would need to go through the geometry and points in a `O(vertices * points)` algorithm with a naïve implementation. Any thoughts on how I should go about the implementation here? Maybe there is an easy way to add this to the framework? (and open a PR with it)

**Comment by qnzhou** [comment]
Note that three values are returned by `pymesh.distance_to_mesh`: http://pymesh.readthedocs.io/en/latest/api_geometry_processing.html#distance-to-mesh-query

The `face_indices` is the quantity you want.  The complexity is `O(num_query_points * log(num_faces))` but it depends highly on the geometry and query location.

**Comment by dragostis** [comment]
Thank you so much for the reply!
