### ISSUE TITLE
link error in libSparseSolver.so

### ISSUE THREAD

**Issue by fundamat** [qnzhou/PyMesh#9]
I have the problem when system try to link shared library libSparseSolver.so 
Is something I missing or configuration not correct?

Linking CXX shared library ../../../python/pymesh/lib/libSparseSolver.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libsuitesparseconfig.a(SuiteSparse_config.o): relocation R_X86_64_PC32 against undefined symbol `malloc@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

**Comment by qnzhou** [comment]
The compiler is complaining your `suitesparse` is compiled as a static library that cannot be linked with a dynamic library (http://stackoverflow.com/questions/13812185/how-to-recompile-with-fpic).  One way around is to recompile `suitesparse` with `-fPIC` flag.  Another way is to skip SparseSolver tool in PyMesh by commenting out line 90 and 91 in [tools/CMakeLists.txt](https://github.com/qnzhou/PyMesh/blob/master/tools/CMakeLists.txt) file.

**Comment by fundamat** [comment]
Thanks! I solve it.
