### ISSUE TITLE
Not using triangulation correctly ?

### ISSUE THREAD

**Issue by gsohler** [qnzhou/PyMesh#95]
# This is a concave polygon
path=[[0,0],[12.5,0],[12.5,12.5],[10,12.5],[10,10],[0,10]]

tri = pymesh.triangle()
	tri.points = path
	tri.split_boundary = False
	tri.verbosity = 0
	tri.run()
	print(tri.vertices)
	print(tri.faces)

Where I get:

[[  0.    0. ]
 [ 12.5   0. ]
 [ 12.5  12.5]
 [ 10.   12.5]
 [ 10.   10. ]
 [  0.   10. ]
 [  0.    0. ]]
[[0 4 5]
 [4 0 1]
 [5 4 3]
 [4 2 3]
 [2 4 1]]

// The Triangle [5,4,3] is incorrect, its outside the original polygon.
Is it a bug or wrong usage ?

**Comment by qnzhou** [comment]
You did not specify `segments`, so triangle is treating your input as a point cloud.  Here is the fix:

```python
#!/usr/bin/env python

import pymesh
import numpy as np
path=[[0,0],[12.5,0],[12.5,12.5],[10,12.5],[10,10],[0,10]]
n = len(path);
edges = np.array([np.arange(n), np.mod(np.arange(n)+1,n)]).T;

tri = pymesh.triangle()
tri.points = path
tri.segments = edges;
tri.split_boundary = False
tri.verbosity = 0
tri.run()
mesh = tri.mesh;
pymesh.save_mesh("out.msh", mesh);
```

**Comment by gsohler** [comment]
Thank for the solution. works brilliant now!

**Comment by gsohler** [comment]
Maybe you are interested to know, that I can greatly use your PyMesh Library in my Project @

https://github.com/gsohler/PythonSCAD

Its a python based OpenSCAD clone. Check its WIKI for details.

Guenther

**Comment by abtin-meysami** [comment]
> Thank for the solution. works brilliant now!

Hello dear @gsohler, sorry do you have any idea on how we can define segments based on existing nodes? The only essential condition is that none of any edges can cut each other.

**Comment by gsohler** [comment]
Sorry for late reply. can you please detail more clearly your intent (maybe with python code ) ?

**Comment by abtin-meysami** [comment]
> Sorry for late reply. can you please detail more clearly your intent (maybe with python code ) ?

You're welcome, thank you for your response, it was solved, I wanted to produce a segment set for generation a Constraint Delaunay Triangulation. I used OpenCV to detect the lines and nodes of a polygon picture then I produced the segment. Again thank you for your following.
