### ISSUE TITLE
MPFR not found, cannot compile CGAL 

### ISSUE THREAD

**Issue by lauphedo** [qnzhou/PyMesh#96]
I cannot compile the third party dependencies although I strictly follow the given guidelines. 
Some problem regarding compilation of CGAL occurs due to not finding MPFR. 
MPFR (i.e. libmpfr4) is installed.
In comparison to that, GMP (i.e. libgmp10) is found. No problem over here. 
Does anyone have the same problem? 
Thank you in advance!

My System: 
Ubuntu 16.04, 64-bit architecture
libmpfr4, libgmp10, libmpc3 are installed and up-to-date.

Given guidelines: 
1. Download Source
```
git clone https://github.com/qnzhou/PyMesh.git
cd PyMesh
git submodule update --init
```

2. Build

Let $PYMESH_PATH be the root directory of the repository. The first step is to compile the optional third party dependencies:

```
cd $PYMESH_PATH/third_party
mkdir build
cd build
cmake ..
make
make install
```

However, when calling `cmake ..` the following error occurs. 
```
.
.
.

== Detect external libraries ==
-- External libraries supported: GMP;GMPXX;MPFR;ZLIB;OpenGL;LEDA;MPFI;RS;RS3;OpenNL;Eigen3;BLAS;LAPACK;QGLViewer;ESBTL;Coin3D;NTL;IPE
-- Preconfiguring library: GMP ...
-- GMP has been preconfigured:
--   UseGMP-file:      
--   GMP include:      /usr/include/x86_64-linux-gnu
--   GMP libraries:    /usr/lib/x86_64-linux-gnu/libgmp.so
--   GMP definitions:  
-- USING GMP_VERSION = '6.1.0'
-- Preconfiguring library: MPFR ...
-- Could NOT find MPFR (missing:  MPFR_LIBRARIES MPFR_INCLUDE_DIR) 
CMake Error at cgal/Installation/cmake/modules/CGAL_SetupDependencies.cmake:66 (message):
  CGAL requires MPFR to be found
Call Stack (most recent call first):
  cgal/Installation/CMakeLists.txt:687 (include)


-- Configuring incomplete, errors occurred!
See also "/home/dominik/PyMesh/third_party/build/CMakeFiles/CMakeOutput.log".
See also "/home/dominik/PyMesh/third_party/build/CMakeFiles/CMakeError.log".
```

**Comment by matplaz** [comment]
Hi, I've got the same issue, and fixed it by installing the following packages (i.e. CGAL separately) :
`sudo apt install libcgal-dev`
`sudo apt install libcgal-demo`

**Comment by madratman** [comment]
Please add this to the readme!
